# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    cobot_arm_group_controller:
      type: cobot_trajectory_controller/CobotTrajectoryController

    gripper_group_controller:
      type: position_controllers/GripperActionController

    vacuum_upper_joint_controller:
      type: position_controllers/GripperActionController

    vacuum_lower_joint_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

cobot_arm_group_controller:
  ros__parameters:
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_group_controller:
  ros__parameters:
    joint: finger1_joint

vacuum_upper_joint_controller:
   ros__parameters:
    joint: vacuum_up_joint

vacuum_lower_joint_controller:
   ros__parameters:
    joint: vacuum_down_joint