site_name: Cobot Documentation
theme:
  name: material

nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Graphical User Interfaces:
    - gui_overview.md
    - howToVNC.md
    - howToXpra.md
  - Configuration: cobot_configuration.md
  - Launch Files: launch_files.md
  - Cobot Model Overview: cobot_model_overview.md
  #- Trajectory Controller: cobot_trajectory_controller.md
  - Hardware Interface: cobot_hardware.md
  - Planner Evaluation: planner_evaluation.md
  - Robot ModelLing: cobot_model/cobot_modelling.ipynb
  #- Hand-eye-calibration: offline_hand_eye.md
  #- Controller Manager: controller_manager.md

plugins:
  - mkdocs-jupyter:
      execute: false   # don't re-run notebooks on build

markdown_extensions:
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
